# Gitpod workspace configuration for Heretix (Phase-1 RPL harness)
# Provides a ready-to-run cloud dev environment using uv.

image: gitpod/workspace-full

tasks:
  - name: Setup uv and deps
    init: |
      bash -lc "curl -LsSf https://astral.sh/uv/install.sh | sh"
      echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
      export PATH="$HOME/.local/bin:$PATH"
      uv --version || true
      uv sync
  - name: Run tests (mock)
    command: |
      export PATH="$HOME/.local/bin:$PATH"
      uv run pytest -q || true

vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance

