version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: heretix-postgres
    environment:
      POSTGRES_USER: heretix
      POSTGRES_PASSWORD: heretix
      POSTGRES_DB: heretix
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U heretix"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
volumes:
  postgres-data:
