"""add stripe customer fields

Revision ID: bf9108335f49
Revises: 9e15719c5c3c
Create Date: 2025-09-17 18:48:37.378848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf9108335f49'
down_revision: Union[str, Sequence[str], None] = '9e15719c5c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('billing_anchor', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'billing_anchor')
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    # ### end Alembic commands ###
